conky.config = {

	own_window = true,
	own_window_type = 'normal',
	own_window_hints = 'undecorated,below,skip_taskbar,skip_pager,sticky',
	own_window_argb_visual = true,
	own_window_argb_value = 0,
	gap_x = 60,
	gap_y = 20,
	alignment = 'top_right',
	use_xft = true,
	xftalpha = 1,
	override_utf8_locale = true,
	draw_borders = true,
	border_width = 1,
	no_buffers = true,
	short_units = true,
	double_buffer = true,
	update_interval = 1,
	template0 = '%H',
	background=true,
	pad_percents = 2,
	


};



conky.text = [[

${font Noto Sans Mono:size=50}$alignc${time %H}:${time %M}:${time %S}${font}

${font Noto Sans Mono:size=14}$alignc${time %A}
${font Noto Sans Mono:size=14}$alignc  ${time %B} ${time %d}  
${font Noto Sans Mono:size=14}$alignc Uptime: $uptime

${font Noto Sans Mono:size=14}	SSD: ${fs_used_perc}%  -> ${fs_used /}/${fs_size /}
${font Noto Sans Mono:size=14}	CPU: ${cpu}%
${font Noto Sans Mono:size=14}	Mem: ${memperc}%  -> $mem/$memmax 
${font Noto Sans Mono:size=12}                    _______________________
${font Noto Sans Mono:size=12}${execi 1 ps -eo pid,ppid,comm,pcpu,rss,pmem,tty --sort=-rss | awk 'NR==1 {printf "  %-15s %7s %9s %8s\n","COMMAND","CPU%","MEM","MEM%"; next} $7 =="?" {printf "  %-15s %7.2f %7.2fGB %7.2f%\n", $3, $4, $5/1024/1024, $6}' | head -n 6}  
${font Noto Sans Mono:size=12}                    _______________________
#${font Noto Sans Mono Medium:size=12} Swap: ${swap} / ${swapmax} -> ${swapperc}%

${font Noto Sans Mono:size=14}                    Temperature: ${hwmon 0 temp 1}°C
]];
