conky.config = {

	own_window = true,
	own_window_type = 'normal',
	own_window_hints = 'undecorated,below,skip_taskbar,skip_pager,sticky',
	own_window_argb_visual = false,
	own_window_argb_value = 0,
	gap_x = 80,
	gap_y = 20,
	alignment = 'bottom_right',
	use_xft = true,
	xftalpha = 1,
	override_utf8_locale = true,
	draw_borders = false,
	border_width = 1,
	no_buffers = true,
	short_units = true,
	double_buffer = true,
	update_interval = 0.5,
	template0 = '%H',
	background=true,
	pad_percents = 2,
	default_color = 'white',
	color0 = 'FFFFFF',
    	color1 = '808080',
	lua_load = '~/.config/conky/conky_renk_degis.lua',
	


};



conky.text = [[
#${font Noto Sans Mono:size=30}${blink Activate Linux}
${voffset 30}${font Noto Sans Mono:size=40}${lua_parse conky_renk_degis}Activate Linux

]];
